baseurl: /diary
author: st98
title: st98 の日記帳
description: st98 の日記帳です。
production_url: https://st98.github.io

encoding: utf-8

permalink: /posts/:year-:month-:day-:title.html
timezone: Asia/Tokyo

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile']

defaults:
  -
    scope:
      path: ''
    values:
      layout: default

markdown: kramdown
kramdown: 
  input: GFM
  auto_ids: true
  hard_wrap: true
  syntax_highlighter: rouge