baseurl: /diary
title: st98 の日記帳

encoding: utf-8

permalink: /posts/:year-:month-:day-:title.html
timezone: Asia/Tokyo

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile']

defaults:
  -
    scope:
      path: ''
    values:
      layout: default

markdown: redcarpet
redcarpet:
  extensions: ['fenced_code_blocks', 'no_intra_emphasis', 'space_after_headers']

highlighter: pygments